apiVersion: v1
kind: Service
metadata:
  labels:
    name: cyanite
  name: cyanite
spec:
  ports:
  - name: graphite
    port: 2003
  - name: pickle
    port: 2004
  - name: api
    port: 8080
  selector:
    name: cyanite
