apiVersion: v1
kind: Service
metadata:
  labels:
    name: graphite
  name: graphite
spec:
  ports:
  - name: http
    port: 2003
  - name: pickle
    port: 2004
  - name: api
    port: 80
  selector:
    name: graphite
